- name: test
  include: ec2_creation.yml
  with_items:
    - elasticsearch-master
    - elasticsearch-data
    - elasticsearch-client

- name: sleep for 60 seconds and continue with play
  wait_for:
    timeout: 60

- name: Populate dynamic inventory with all created instances
  include: add-host.yml
  with_items:
    - elasticsearch-master
    - elasticsearch-data
    - elasticsearch-client
