- hosts: localhost
  vars_files:
    - "../vars/default.yml"
  
  roles:
     - { role: ec2-creation }


- hosts: all
  become: true
  vars_files:
    - ../vars/default.yml

  roles:
     - { role: elastic-stack }
