- hosts: localhost
  vars_files:
    - "../vars/3rdparty/sample.yml"
  
  roles:
     - { role: ec2-creation }


- hosts: all
  become: true
  vars_files:
    - ../vars/3rdparty/sample.yml

  roles:
     - { role: elastic-stack }
